development:
  main_cache: ['127.0.0.1:11211']
  redis_host: '127.0.0.1'
  redis_port: 6389
  http_procs: 1
  workers: 1
  port: 3000
  run_as: reco
  pid: /var/run/
  logs: /var/log/nutsie_radio
  rotate: daily