# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{lamed}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Lee Chang"]
  s.date = %q{2010-01-19}
  s.description = %q{Yet another LaMe Ruby Web Framework}
  s.email = %q{leetchang@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lamed.gemspec",
     "lib/lamed.rb",
     "lib/lamed/controller.rb",
     "lib/lamed/helper.rb",
     "lib/lamed/initializer.rb",
     "lib/lamed/main.rb",
     "lib/lamed/model.rb",
     "lib/lamed/object_loader.rb",
     "lib/lamed/redis.rb",
     "spec/examples/conf/config.yml",
     "spec/examples/conf/database.yml",
     "spec/examples/config.ru",
     "spec/examples/ext/controllers/hello_world.rb",
     "spec/examples/ext/controllers/lamest/bar.rb",
     "spec/examples/ext/controllers/lamest/foo.rb",
     "spec/examples/ext/models/bar_model.rb",
     "spec/examples/ext/models/foo_model.rb",
     "spec/examples/ext/views/hello_world.mustache",
     "spec/examples/ext/views/lamest/bar.mustache",
     "spec/examples/ext/views/lamest/foo.mustache",
     "spec/examples/lib/foo_lib.rb",
     "spec/helpers_spec.rb",
     "spec/initializer_spec.rb",
     "spec/lame_spec.rb",
     "spec/object_loader_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/onemorehill/lamed}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Get LaMeD}
  s.test_files = [
    "spec/examples/ext/controllers/hello_world.rb",
     "spec/examples/ext/controllers/lamest/bar.rb",
     "spec/examples/ext/controllers/lamest/foo.rb",
     "spec/examples/ext/models/bar_model.rb",
     "spec/examples/ext/models/foo_model.rb",
     "spec/examples/lib/foo_lib.rb",
     "spec/helpers_spec.rb",
     "spec/initializer_spec.rb",
     "spec/lame_spec.rb",
     "spec/object_loader_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rack>, [">= 1.0"])
      s.add_development_dependency(%q<mustache>, [">= 0"])
    else
      s.add_dependency(%q<rack>, [">= 1.0"])
      s.add_dependency(%q<mustache>, [">= 0"])
    end
  else
    s.add_dependency(%q<rack>, [">= 1.0"])
    s.add_dependency(%q<mustache>, [">= 0"])
  end
end

